### ISSUE TITLE
Migrate from DraftJS to ckEditor

### ISSUE THREAD

**Issue by nazar** [mikelax/forgingadventures#102]
- [x] Replace game lounge message create/edit with CKEditor
- [x] Replace game messages create/edit with CKEditor
- [x] Implement message quotes in both game lounge and game messages
- [x] add plugin for adding text color (for now this will be the method for in character styles - i.e. singing, thinking, etc...
- [x] add plugin for image uploads for both game messages and game lounge messages

**Comment by mikelax** [comment]
Can the "inline" custom styles be set up as:  

Talking - bold and custom color ( I think in a separate ticket we should rename "shout" to "talk"
Thinking - custom color and italic
Singing - ?? same formatting as what was used in draftjs for now

**Comment by mikelax** [comment]
This is looking really good. So to get the game styles working (talk, think, sing) would we implement in tinymce with [custom formats](https://www.tinymce.com/docs/demo/format-custom/)?
