### ISSUE TITLE
Implement Custom Styles for Game Message Formats

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#108]
Overview
===
As a Player in a Game, I want to be able to easily select from pre-formatted styles for common formats such as:  Talking, Thinking, Singing.

Requirements
===
These custom styles will be implemented with tinymce [custom formats](https://www.tinymce.com/docs/demo/format-custom/)

Here is the list of formats that we should have. This should be listed in the menu Dropdown in this order. 

* Paragraph - this is the regular, default text that will be used in textarea
* Header - This is a message header, it can be formatted as the current Header 2
* Character Talking - This will be the character talking text. It should be bold, and have a color to it.
* Character Thinking - This is character thinking, it should be colored, bold, and italics. 
* Character Singing - This is singing text, it should be colored, italics, and indented one group.

**NOTE**, in a future version, we can allow the user to select a "Color Palette" for their messages, and this will then be used to format (color) IC message formats such as Talking, Thinking, and Singing.

The existing `Header 3` format can be removed, and `Header 2` can be renamed to `Header`

**Comment by mikelax** [comment]
@nazar  is this how we'll implement? Did you already find something that talked about how to insert the custom "music" characters before and after a format? 
It would also be cool to use a "thought bubble" to surround the thinking format.

**Comment by nazar** [comment]
Hey @mikelax 

>is this how we'll implement? Did you already find something that talked about how to insert the custom "music" characters before and after a format?
It would also be cool to use a "thought bubble" to surround the thinking format.

Thanks for this - I didn't spot it. We should be able to use custom formats as are able to assign a class. Once we have a class we can use the `:before` and `:after` pseudo elements to surround text with icons. I'll also look if the custom format allows adding more than just a span - i.e. HTML.

I'll have a think on how best to surface these only on game messages and not the lounge.

**Comment by mikelax** [comment]
@nazar cool. For the game vs lounge editor, isn’t the only female difference in the initial config of the editor? 

So could we make the component take a prop for the “type” of editor to create? Ie. Lounge vs game?

**Comment by nazar** [comment]
>So could we make the component take a prop for the “type” of editor to create? Ie. Lounge vs game?

Yep - I was thinking along the same lines
