### ISSUE TITLE
Modify Character create/edit page to use label specific Form Component

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#115]
Overview
===
As a User, when I create a new Character, I should be able to enter values for character attributes based on the _Game Label_ selected for the Character. 

Requirements
===
* On the create page, after the User selects a Label, the Form component for the given Label should be displayed. 
* Since the exact fields are still being defined in #114, this ticket can have a single textfield and custom text copy for each of the labels to show the process is picking up the correct form for a given Label. 
* We can limit the scope of this ticket to that of the all the UI components and logic. We'll do the work of updating mutations, new db column, etc. in a separate ticket. 

Nice to Have
---
* If the User selects a Label, enters some values into the Form, then changes the Label to a different value, the page should prompt the User with a confirm dialog asking if they are sure they want to change the Label and it will reset the Custom Attributes. 

Questions
===
1. After the initial create, should we not allow the User to change the _Game Label_ when editing a Character?
1. Should we make the create character a two step process, where the first step allows the user to select a label. Then for the second step we know the exact form to display? Otherwise on a single page, the "bottom half" of the form will get changed after the Game Label value is selected. 
  1. I _think_ I would prefer to keep the process to a single page, but open to your thoughts.

**Comment by nazar** [comment]
Hey @mikelax 

>After the initial create, should we not allow the User to change the Game Label when editing a Character?

I'm thinking no as it can get a bit weird. I.e. what happens with attributes that don't exist between labels. 

>Should we make the create character a two step process
>I think I would prefer to keep the process to a single page

I'm more tempted with a single page as well but one gotcha I can think of is how to handle filled form changes when labels are changed. I.e. player select DnD label, starts filling out the form then goes back and select the Pathfinder label. Maybe disable the label select once the character form is dirty?

**Comment by mikelax** [comment]
I kind of like the single page. Maybe if form is dirty we just present confirm saying custom Data will be lost by changing label.   

Also agree user shouldn’t be able to change label in edit.  It’s not needed and too complicated to handle.

**Comment by nazar** [comment]
Hey @mikelax 

Is [this the correct document](http://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf) to reference races, classes, etc? I was looking through the DnD basic rules and those only list a subset.

**Comment by mikelax** [comment]
@nazar that srd contains the main races, but it might be missing a few from 5e.  Also it doesn’t have the sub races.  I can send you the full list of values tonight

**Comment by mikelax** [comment]
Also there are a few sub races for each main race. 
I just realized I didn’t include a field in schema for subrace. I can either add, or we do a single drop down with labels like 

Id: label
10:  Elf
11:  Elf - Wood Elf
12:  Elf - Dark Elf
Etc
