### ISSUE TITLE
Tidy up client routes and auth object

### ISSUE THREAD

**Issue by nazar** [mikelax/forgingadventures#12]
Tasks

- [x] refactor API JWT handling. Currently the [graphql](https://github.com/mikelax/forgingadventures/blob/master/api/middleware/security.js#L33) related middleware makes a call to `checkJwt` for each request, which adds a considerable amount of latency (between 200 and 800ms on my dev). This is either due to the library making a remote call or some other reason. In either case, the latency issue needs to be addressed via either correct use of the JWT auth0 library or via locally caching the JWT until it expires.

- [x] refactor [Auth](https://github.com/mikelax/forgingadventures/blob/master/client/src/components/App/App.js#L21) so that it can be passed as a prop to any component irrespective of its position in the DOM tree. 

- [x] Incorporate the auth state into the router so that login redirects can be implemented outside of components and views.

**Comment by nazar** [comment]
> In either case, the latency issue needs to be addressed via either correct use of the JWT auth0 library or via locally caching the JWT until it expires.

Possibly related/solutions

* https://github.com/auth0/node-jwks-rsa#caching

**Comment by mikelax** [comment]
@nazar it sounds like we do need to turn on caching.  
Part of verifying the checkJwt function involves making an api call to Auth0 to get a private key to decrypt the jwt.  

It sounds like caching in that lib is the way to go.

**Comment by nazar** [comment]
Yep - I was using the jwt library incorrectly. It actually has remote key caching built-in and enabled by default. The way I was using it meant that the cache was re-built on each call #fail. Tis fixed now.
