### ISSUE TITLE
Update game messages create component to add post type

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#127]
Overview
===
As a user that already joined a game, I want the ability to create either an in character (IC) or out of character (OOC) post type when creating a new post in the game messages tab.  

Requirements
===
When creating a post, it should default to creating an in character post on initial page load, or after form resets. 
Above the text area, a “mock” post header should display to indicate to the user who the post is being created as.  It should display the profile image and name of either the user or character.  
There should be an “arrow” or UI element the user can tap to allow switching between user and character.  

A new attribute will have to be added to the posts model and db table to store the post type. 
Lets call the field:  postType not null
For the migration it should add the column as null, update existing rows in table to have value if ic, then as third step make column not null. 

Future enhancements 
===
In addition to allowing the user to change post type, we will also allow other actions to be made such as:  add dice roll, maybe image upload gets broken out into separate action, etc. 

Questions
===
Should postType be int or varchar or bool field?
I was thinking varchar with values of ic or ooc

**Comment by nazar** [comment]
>Should postType be int or varchar or bool field?

enums ftw!
