### ISSUE TITLE
Error viewing Messages page with no character selected for player

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#145]
Overview
===
there is a logic bug right now that can occur in the following conditions:

1. As a player, join a game but do not select a character when joining. 
1. As the GM for the game, accept this new player
1. Back as the player, navigate to the Game Messages page. You will receive the error below, the issue is related to not having a character selected, but currently the `InCharacterHeader` assumes a character. 

Instead the header should render as some type of N/A or "Still working on it" display.

```
TypeError: Cannot read property 'labelId' of null
./src/components/Games/View/components/GameMessages/InCharacterHeader/index.js.__webpack_exports__.a
src/components/Games/View/components/GameMessages/InCharacterHeader/index.js:18
  15 | 
  16 | import './InCharacterHeader.styl';
  17 | 
> 18 | export default function(props) {
  19 |   const { character, character: { labelId } } = props;
  20 | 
  21 |   const PrimaryAttributes = {
View compiled
```

**Comment by mikelax** [comment]
hey @nazar  what do you think we should do for this ticket? 
I don't think we need to worry about adding logic preventing the user from creating messages, at least not for v1. 

Should we just display the header as a "Still Working on it" similar to the Player list on the Overview page?

**Comment by nazar** [comment]
Hey @mikelax,

>I don't think we need to worry about adding logic preventing the user from creating messages, at least not for v1.

I'm slightly tempted with this solution as it might be easier to implement.

I'll have a look at these two options; should we consider blocking from posting unless a character is selected if it is easier to implement?

**Comment by mikelax** [comment]
@nazar  if you think that is the easier use case to solve, then I am ok with implementing that, What would the UI look like if the user tried to get to the messages page without having a character? Would they see the messages but would not see the `CreateMessage` component, but instead a text notice about selecting a character before being able to post?

**Comment by nazar** [comment]
>Would they see the messages but would not see the CreateMessage component, but instead a text notice about selecting a character before being able to post?

Yep and show a message similar to  the "please join before..."
