### ISSUE TITLE
Tidy Project Folders

### ISSUE THREAD

**Issue by nazar** [mikelax/forgingadventures#147]
Restructure folder structures as follows:

**client folder**

1. The shared components are currently under `client/src/components/shared/components`. Move all shared components to `client/src/components/shared`

**api folder**

1. Extract both the `migrations` and `seeds` folders from `api` and move both into a new top level folder named `database`. This will allow us to define a separate `Dockerfile` for database migrations and loading seeds. This should also make it easier for us to orchestrate creating and seeding a local database for integration/e2e testing via the top level `package.json`. 

2. Add an `api/src` folder and move the following folders into it: `loaders`, `middleware`, `models`, `routes`, `schemas`, `services` and `utils`. This will allows us to simplify both the `dev` and `prod` webpack config files by removing the [alias sections](https://github.com/mikelax/forgingadventures/blob/master/api/webpack.dev.js#L35-L40) and replacing it with a single `module-resolver` plugin section in [package.json](https://github.com/mikelax/forgingadventures/blob/master/client/package.json#L133-L141)

**root folder**

1. Add a `tests` folder - this will contain both a `integration` folder for API integration tests and `cypress` for cypress tests. We should then be able to add a Dockerfile to each folder to build testing containers (for use in CI, for example).

**Comment by nazar** [comment]
Hey @mikelax - I'd like to tweak folder structure a "little"  and opened this ticket for details and discussion. Any thoughts or questions?

**Comment by mikelax** [comment]
Hey @nazar I went through the list of proposed changes and all seem to make sense. I had notes for some of the changes anyway so now is as good a time as any. Lets do it.
