### ISSUE TITLE
Add and Improve Paging

### ISSUE THREAD

**Issue by nazar** [mikelax/forgingadventures#160]
Revisit paging in the games page and use paging as described [here](https://blog.logrocket.com/rendering-large-lists-with-react-virtualized-82741907a6b3). Ideally, we should use cursor based paging - revisit graphQL docs for any pointers.

Implement paging in:

* game lounge
* game messages

**Comment by mikelax** [comment]
@nazar  is this a dup of #40 ? If so want me to close 40?
