### ISSUE TITLE
Implement User "Read Indicator" for Game Messages

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#177]
Overview
===
As a user participating in a Game, when viewing Game Messages, I want an option to click to indicate I have read up to a certain point in the Messages Thread. The idea is basically to implement a bookmark that the User can manually move as they read through the Messages. 

The "Bookmarks" will be viewable to the other Players and GM in the Game, but not public Users viewing the Game. 

Requirements
===
The data to track how far along a player is within a game can be stored as a new column on the `game_players` table. 

### Simple Mock up
![progress_indicator](https://user-images.githubusercontent.com/2080701/43092356-f75f95b6-8e7a-11e8-9a34-61e206c0ebfa.png)

**Comment by nazar** [comment]
Hey @mikelax 

I need a second opinion on naming (names r so hard) the table, considering that we also plan to add a second "bookmark" feature into game messages for players to bookmark any message.

Table candidate names:

* game_message_read_bookmarks
* game_message_read_progress
* game_message_read_indicators
* game_message_progress
* mike_can_think_of_a_good_table_name

**Comment by mikelax** [comment]
@nazar maybe we should stay away from the term `bookmark` for this feature, as it will then be confusing when we introduce actual bookmarks. 

how about a table name of:  `game_players_progress`?
Also, as an option, do you think we should store the attributes in the `game_players` table? Or is that overloading the use of that table?
