### ISSUE TITLE
Architecture - Determine image upload lib and storage

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#28]
Overview
===
There are several features of the application that will need to support image uploads from the user. This ticket will cover:

1. the discussion and options to decide on the React (client) file upload library and server API
1. the file storage, CDN delivery, and responsive image generation

Discussion
===

Client & API Lib
---
- Unlike in DS, we can have our (web) client interact only with our server API, instead of interacting with any third party platforms, ie. S3, SaaS image service, etc. This also abstracts away the backend storage and logic from the client, thus making it easier to make a change. 
- [react-dropzone](https://github.com/react-dropzone/react-dropzone) seems like a very functional and popular library. Only *potential* issue is that there is currently a call for new maintainers. 

Storage, Delivery and Responsive lib
---
- We have a couple of different options for how we want to handle storing and generating responsive images. 
  - One approach would be something similar to what we did in DS, we upload to an S3 bucket and have that trigger a lambda function to create a set of known dimensions. Pros are that it would be super easy to implement. Con is that its not as extensible if you need additional image sizes, etc. 
  - Second option would be to use a responsive image service. These are SaaS platforms that handle everything for you, image storage, delivery, and real-time responsive image generation and manipulation. Pros are they are more extensible going forward, pretty easy to implement. Con is 3rd party dependency and potential higher cost. 
    - Two options are:  [cloudinary](https://cloudinary.com/solutions/image_management) and [imgix](https://www.imgix.com/)

Approved Architecture
===

Client & API Lib
---
[react-dropdown](https://react-dropzone.js.org/) is as close to an "official" react file upload lib as exists. If drag and drop upload support is needed, then this should be the lib to use. [Here is a quick tutorial](https://medium.com/technoetics/handling-file-upload-in-reactjs-b9b95068f6b) showing it's usage.

Otherwise it can be regular javascript html5 file upload. 

Storage, Delivery and Responsive lib
---
[Cloudinary](https://cloudinary.com/) will be used as the platform to store and serve the responsive images. To provide flexibility going forward all file uploads will also be uploaded to S3 in addition. This way we already have all source images if we choose to move to a different platform or implement in-house in the future. 

[Responsive images](https://cloudinary.com/features/responsive_images) and resizes are very easy to handle.

**Comment by nazar** [comment]
`react-dropzone` looks [interesting](https://css-tricks.com/image-upload-manipulation-react/). 

In terms of image processing - [gm](https://github.com/aheckmann/gm) with [GraphicsMagic](http://www.graphicsmagick.org/) is stable and popular.

**Comment by mikelax** [comment]
@nazar  FTW, cloudinary with S3 backup and react-dropzone for file uploads and storage. 
[Responsive images](https://cloudinary.com/features/responsive_images) are automatically handled.
