### ISSUE TITLE
Implement shadow (local) users table in postgres

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#3]
## Overview

After doing some reading on various tutorials and [posts](https://community.auth0.com/questions/802/few-questions-regarding-crud-and-users), I think that we will need to implement a users table in the main postgres database. This table will store the Auth0 user_id column, along with a set of metadata needed by the website to function and provide all data to the UI for display (ie. user profile image). 

We will implement a similar solution as the community answer above that creates a two-way link between the pg users table and Auth0 users table. 

## Development Tasks

- [x] Migration for pg users table & foreign keys
- [x] Auth0 rule for login
- [x] (Rest) API to create user record in pg table. Params of Auth0 user_id, user and app metadata, response of pg user id
- [x] Add users seed and refactor games seed
- [x] Refactor games and messages insert to include user id

## Questions:

1. Do we need to create a user id (pk) attribute in pg table, or can we use the Auth0 user_id field as the primary key in the pg users table?  Yes, we will use internal pg userId. It will be added to Auth0 app_metadata

I created [this question on the Auth0 community](https://community.auth0.com/questions/12656/best-practice-for-storing-user-profile-attributes) site to see if I can get any better answers that what I was able to find from random googling.

**Comment by nazar** [comment]
>Do we need to create a user id (pk) attribute in pg table, or can we use the Auth0 user_id field as the primary key in the pg users table?

That depends on how auth0 can handle a single user that uses multiple auth methods - i.e. all of google, twitch and email. It also depends on whether auth0 provides a mechanism that allows a user to merge say google and twitch logins into a single profile and always return the same user_id despite the user's choice of auth provider.

In terms of `users.id` I think all tables should have a pk based on a sequential INT id - if anything just for consistency that all tables have an INT id as that would simplify the underlying code. If auth0 allows for the both the scenarios covered in the prev paragraph then we can record the auth0 user id and use that as an alternate key. We might need an additional table if auth0 does not cover the scenarios described above - I haven't had a chance to deep-dive into auth0 docs yet :)

**Comment by mikelax** [comment]
@nazar the good thing is that auth0 does autmatically handle all the use cases you pointed out. 
Based on the OIDC implementation, we can guarantee that a user_id we receive back from auth0 will be unique. This includes all different auth methods we choose to support, if a user auths with one mechanism, then "adds" another method. 

The gotcha is that the data type must be a varchar. For example here is the user_id for my user that logged in via twitch:  `oauth2|twitch|111111111`

**Comment by nazar** [comment]
>the good thing is that auth0 does autmatically handle all the use cases you pointed out. Based on the OIDC implementation, we can guarantee that a user_id we receive back from auth0 will be unique

❤️  ❤️  ❤️ 

>The gotcha is that the data type must be a varchar. For example here is the user_id for my user that logged in via twitch: oauth2|twitch|111111111

How about the `users` table having both an `id` INT pk and a second unique `authUserId` alt key. We use the int 'id' as the fk for mainly two reasons:

1. DB level implementation _might_ be simpler if all PKs are INT id
2. DB level implementation _might_ be simpler if all FKs reference an an INT id

**Comment by mikelax** [comment]
@nazar  yeah I think that is fine. that also gives flexibility if we want to drop auth0 at some point in the future, the ID is independent. Also I heard (probably rumors years ago) that using INT as FKs instead of strings is faster, but I don't know if that is actually true or not.

**Comment by mikelax** [comment]
Closed by #19
