### ISSUE TITLE
Add support for Applying & Joining a Game

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#30]
Overview
===
As a user, after reading the details of a Game, and possibly posting in the Game lounge, a user will want to Join a Game. As part of making a Post in the Lounge, a User will be able to apply to join the Game. The user will optionally be able to enter a message, but at the very least the act of applying will create a message such as:  _Michael has applied to join the Game!_

This ticket will mainly cover the DB schema, methods and use cases for joining and the GM accepting players. A (basic) prototype UI can be added to the Game Details / Lounge Page. 

Requirements
===
A user may apply to a Game, this will put the User in the initial state of:  "**pending**".
The GM of the Game may then update the status of the User to:  "**accepted**", or "**rejected**".
Though unlikely, a User may apply to the same game more than once.

A User must be logged in to create a Post in the Game Lounge and Join a Game. If the User is not logged in and clicks the Join button they should be redirected to the Login page.

Technical Details
---
For this ticket we will only handle the use case of a User applying to a game. A future enhancement to this ticket will allow for the User to optionally select a new or existing character to include when joining the game. 

The db needs to support the use case of a user joining a game with a nullable (blank) character. The character can be filled in at a later point in time. 

Database Tables
---
Here is a list of possible changes to support this feature. 

**game_players**
id, userId, createdAt, status (pending, accepted, rejected, quit, kicked), updatedAt, deletedAt
Once we add the concept of characters, a nullable characterId will be added. 

UI Implementation
---
In this ticket we will implement a basic UI to all for the following use cases:
* Joining a Game
* Viewing the status of Players in Game
* Allow GM of a Game to accept a Player

We will add a new tab on the View Game page between the existing two existing Tabs. The new tab name will be called:  "Players"
The new tab will show a table of the players in the game that have a status of pending and accepted. Rejected and kicked status, etc players will not be displayed. 
Above the table will display the number of min, max, and current accepted players.
The table will display the following information: 
User Profile Image, Name (Timezone if set up already)
Status
In a future ticket we will add character information such as:  Profile Image, Name, Level, Race, Class

Join Game
---
A new button will be added to the View Game "header" where the game title, scenario is displayed above the tab bar. The button should be right aligned. The label should be:  **Join Game**
It should change to a disabled state of "Joined"  if the user is currently accepted or the game-master. 
It should be a disabled state with a label of "Pending" if the user is pending. All other states (ie. rejected, etc) should display the default **Join Game**.

After clicking the Join Game button, the user should go to a new page with the url:  /games/:id/join
There should be a message textarea like on the game lounge tab. 
The textarea should display by default, in italics: ":name has applied to join the game"
The should then be copy on the page to inform the user they can add to this message with any specifics about their character, or notes to the game master. 
There should then be submit and cancel buttons at the end of the form. either option should take the user back to the View Game page.

**Comment by mikelax** [comment]
@nazar  I added a section for how the Join Game user flow could work, let me know your thoughts. I also thought about skipping the /join page for the MVP until we add the concept of character.

**Comment by nazar** [comment]
@mikelax - the Join Section looks good. One thing I was thinking about, which may be relevant to this, is to rename the current [GameLoungeMessage](https://github.com/mikelax/forgingadventures/tree/master/client/src/components/Games/components/GameLoungeMessage) componet to RichEditor (or equivalent) so that we can re-use on other parts of the UI. 

I think for this story, the initial implementation would just use a textedit control. I can then refactor the code in separate ticket to utilise the RichEditor so that we can apply the formatting (i.e. italic).

**Comment by mikelax** [comment]
@nazar  yeah I agree. also the *RichEditor* can probably be pulled out of the games src folder as it *could* be used even for other sections of the app besides the "Game".
