### ISSUE TITLE
Create Game Lounge

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#31]
Overview
===
As a user, after searching and finding a potential Game to Join, I will want to view and Post in the Game Lounge. This will be discussion about the meta of the Game, ie. potential players asking questions, posting character ideas, etc. This discussion will *not* be part of the Game itself. It will not be part of the IC or OOC, what we currently have implemented as the _game_messages_ table. 

Requirements
===
The Post "widget" should be the same widget that is used to make game messages pots. We may just want to disable a few of the toolbar options such as IC, Singing, Etc. 

The User must be logged in to create a Post in a Game Lounge. 

The messages will be displayed in chronological order

Questions
---
Should this be implemented as a sibling table to _game_messages_? ie. game_lounge? How would we make use of a commentable pattern that you mentioned a while back? Is that overkill for this use case?

**Comment by nazar** [comment]
>Should this be implemented as a sibling table to game_messages? ie. game_lounge?

👍 

>How would we make use of a commentable pattern that you mentioned a while back? Is that overkill for this use case?

Yeah it might be overkill for this use-case as it would be simpler to implement a concrete table for this as opposed to a polymorphic table

>The Post "widget" should be the same widget that is used to make game messages pots. We may just want to disable a few of the toolbar options such as IC, Singing, Etc.

I was thinking of creating a ForumMessage component instead, which is also based on the draft editor. These two "message" components would be separate as the ForumMessage component would be easier to implement as draftjs already provides [richedit components](https://draftjs.org/docs/api-reference-rich-utils.html#content) (i.e. bold, italic, etc) leaving us just to implement a handful of specific ones - i.e. qoute block, which can reference the same quote block component used in the GameMessage component.

**Comment by mikelax** [comment]
sounds good @nazar . I guess with the components being pretty small to begin with having a "duplicate" for the forum posting isn't a big deal as the actual code snippet is pretty small.
