### ISSUE TITLE
Make UI handle expired JWT Tokens

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#43]
Overview
===
There is currently a bug on the UI as to how it handles expired JWT tokens. If the UI thinks the user is still logged in (ie. cookies exist) but the token in the cookie is expired then currently the game messages errors out. This is due to it making graphql calls with the expired token instead of redirecting to the login page. 

Requirements
===
I have run into this use case leaving my browser open. In this case I *think* the system that renews the token by hitting the /silent page should handle this, but there might be a bug in that logic. 

Also, we probably should also have the UI itself set up to handle receiving *unauthorized* HTTP responses and redirecting back to the login page. 

<img width="1214" alt="screen shot 2018-01-16 at 4 07 15 pm" src="https://user-images.githubusercontent.com/2080701/35012448-c8adca26-fad7-11e7-8ae3-7b358df129e6.png">

**Comment by mikelax** [comment]
hey @nazar  I think this issue is still happening. I just checked out your new 53 branch to test it, the dockers containers were already running so they recompiled because of the changes. My web browser was already on the /games page, after reloading I received the same error I had been receiving when there is a jwt token in the browser storage but its expired. 

Here is stack trace: 
```
api_1     | UnauthorizedError: jwt expired
api_1     |     at /app/node_modules/express-jwt/lib/index.js:102:22
api_1     |     at /app/node_modules/jsonwebtoken/verify.js:27:18
api_1     |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
api_1     |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Here is web browser stack trace
<img width="1159" alt="screen shot 2018-01-27 at 8 08 01 am" src="https://user-images.githubusercontent.com/2080701/35472240-70bf6a62-0339-11e8-97f0-15a1d2d4bc0f.png">

**Comment by nazar** [comment]
I'll re-open 👍

**Comment by nazar** [comment]
I'm seeing this error when the UI attempts to re-authorise a token - digging deeper

<img width="1412" alt="screen shot 2018-01-27 at 13 56 36" src="https://user-images.githubusercontent.com/6967/35472608-100eead6-036a-11e8-8529-6fc46d1ecec5.png">

**Comment by mikelax** [comment]
hmm, maybe that is related to helmet security installed on the express server?

**Comment by nazar** [comment]
Yeah, I thought it was helmet as well but I was seeing the same message with the helmet middleware commented out.

What I did do is update the lib to `https://cdn.auth0.com/js/auth0/9.0.2/auth0.min.js` [here](https://github.com/mikelax/forgingadventures/blob/master/api/views/pages/silent.ejs#L5) to match the `auth-js` version we have on the client.

I'm not getting the error anymore but am getting a timeout message instead [here](https://github.com/mikelax/forgingadventures/blob/master/client/src/services/webAuth.js#L69)

<img width="733" alt="screen shot 2018-01-27 at 14 34 02" src="https://user-images.githubusercontent.com/6967/35472886-55fe1756-036f-11e8-8e1f-cb89dc026892.png">

**Comment by mikelax** [comment]
I found a few articles that might be related to this issue. Long story short, it seem that renewAuth and "silent" might have been superseded  by a new `checkSession` function. 

https://community.auth0.com/questions/12177/auth0-renewauth-in-react-returning-timeout-error
https://auth0.com/docs/libraries/auth0js/v8#using-checksession-to-acquire-new-tokens
https://github.com/auth0/auth0.js/issues/564

**Comment by nazar** [comment]
Yeap - I've been looking at `checkSession` as well and tried that but keep getting the following error message as documented [here](https://auth0.com/docs/libraries/auth0js/v8#using-checksession-to-acquire-new-tokens):

>If the connection is a social connection and you are using Auth0 dev keys, the checkSession call will always return login_required.

That's the same error message I am getting in the silent page in the `webAuth.parseHash` callback:

`{error: "login_required", errorDescription: "Login required", state: "FA5BAblZrKwXEcI6O0Lp7zcxxDd7uNjN"}`

😿

I googled for that error but didn't find anything helpful. I think I might leave this for now 🐼

**Comment by mikelax** [comment]
hmm, yeah 😢  one last option, what if you try using an email/password user for the testing. maybe that will prove the logic is correct or not. if that doesn't work then we can park this for now.
