### ISSUE TITLE
Add ability to attach an image to a game

### ISSUE THREAD

**Issue by nazar** [mikelax/forgingadventures#58]
Update the create game view to accept an image. Refactor the users API endpoint to accept both profile and game images.

**Comment by mikelax** [comment]
@nazar  should the existing users API be refactored, or should we create a more general "file/asset" upload to be used for games, etc.

**Comment by nazar** [comment]
>should the existing users API be refactored, or should we create a more general "file/asset" upload to be used for games, etc.

Hey @mikelax - I was thinking about this last night and I agree that a general `file/asset` might be a better approach. We'll just have to pass an extra key/value in the body signifying what is being passed - i.e. `userImage`, `gameImage`, `messageImage` etc and maybe set sizes accordingly. Sizes could also be handled in the UI using the `publicId` value.

**Comment by mikelax** [comment]
@nazar  exactly right RE. the `publicId` value. We will just have to add one constant to the react project which is the "base url" for the cloudinary domain, it's basically our account name. 

RE. the general API, are you thinking of leaving the existing user profile image upload but refactor the logic so it is shared with the new file/asset API? That way some of the additional user profile image logic remains in tact.

**Comment by nazar** [comment]
>We will just have to add one constant to the react project which is the "base url" for the cloudinary domain, it's basically our account name.

👍 👍 👍 👍 

>the general API, are you thinking of leaving the existing user profile image upload but refactor the logic so it is shared with the new file/asset API? That way some of the additional user profile image logic remains in tact.

Still thinking about this but I'm tempted to extract the functions in `routes\usersImpl.js` to a service module called something like `cloudinary` which can then be re-used in route controllers. Still mulling it through though.
