### ISSUE TITLE
Display issue on games list page, newly created game is added twice

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#69]
Overview
===
After creating a new game on the /games/create page, as a user I am redirected back to the /games list page. The newly created game is displayed in the list twice. We have seen this bug present itself if this game was the first game ever created, or if there were already two games created. 

@nazar believes the issue may be related to infinite load. 
>I have a feeling it is an issue with the infinite load - i.e the page view and the inf load both trigger at the same time

<img width="1157" alt="screen shot 2018-02-08 at 8 33 28 am" src="https://user-images.githubusercontent.com/2080701/35975749-cf52eb78-0cab-11e8-9035-4644abe3130c.png">

**Comment by nazar** [comment]
Thanks @mikelax - as an aside, I set the row width to 4 cards in the games list page. Do you think that is too squished as we should display 3 cards per row instead?

**Comment by mikelax** [comment]
The images are a little tall vertical. maybe try a version that is three across so the cards (and cover images) are a bit wider? Also, not sure if you do already but we may need to set up the overview (and scenario) to be be truncated so they don't run too long. Not sure if semantic handles that automatically for you.
