### ISSUE TITLE
Implement Game/Forum Post Interface

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#7]
Overview
===
This ticket covers the work to integrate the main "create post" text window. It will be implemented as a type of rich text editor (RTE). This will be one of the most common interactions the user will have with the site so the UX and how well it works will be critical. 

Requirements
===

- The editor should easily allow the user to create the different types of "text", and actions within a single post. 
- The initial set of text types are:  Character Talking, Character Thinking, Character Signing, Regular Text. 
- As discussed on a call, a game will primarily consist of a single game thread. This thread will be made of posts of different types. Everything will be displayed chronologically in a single feed so its easy to always have context around a post. 
   - The initial post types will be:  In Character (IC), Out of Character (OC)
   - TODO is how to handle additional types such as dice rolls, DM actions such as "call for initiative"
   - This will be handled in separate tickets, it's listed here just for context around this chat interface. 
- The best UX for this interface is that the text markup renders correctly as the user is creating the post. If this proves too difficult, the next best option would be to give them a "preview" tab that they can easily switch between typing and previewing. Example UX would be the github issue/comment UI widget

Possible libraries
---
[react-quill](https://github.com/zenoamaro/react-quill)
[draftjs](https://draftjs.org/)
[react-rte](https://github.com/sstur/react-rte) - based on draft js. Not sure if we need this or would write our own similar to this lib based on draft.  
[this reddit thread](https://www.google.com/amp/s/amp.reddit.com/r/reactjs/comments/5o6eh6/which_wysiwyg_editor_is_recommended_with_react/) talks about history of draft. Lots of projects after it was released but a lot are stale now. Need to research them more. Draft is the building blocks to create own editor. Careful though as there are mobile issues and shims possibly needed for create react app. 
[marked](https://github.com/chjj/marked)

**Comment by mikelax** [comment]
@nazar  one thing I was thinking about this am, as you are going through the changes with draft, once you get to a logic point you should make sure that the full utf8 unicode char set is allowed. ie. we want to allow full emoji and special character usage. If we need to make any db conf changes to set the db in the correct charset or collation we should do so to make things easier.

**Comment by nazar** [comment]
Yep yep re utf-8 and emojis. Draft supports emoji's provided the page has a `<meta charset="utf-8">` in `<head>`, which it has.

I _think_ pg `utf-8` support 4bit unicode - we'll just have to make sure the DB is set to `utf-8` charset when it is created.

I just added an emoji to a game message and it saved and displayed it correctly 👍  - yay PG 💥

**Comment by mikelax** [comment]
Closed by #18
