### ISSUE TITLE
Implement game_labels db, model, and objects

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#8]
Overview
===
This ticket will cover the work to implement all objects related to the concept of game_labels. 
We are specifically calling this object labels instead of tags to indicate that these are related to application and logic, and not more general user-created tags. 

Requirements
===
After much discussion on the trello ticket and in chat, we have decided to implement a table structure similar to below. There will be a single label, then aliases that can be also be used as a lookup (ie. by user when searching) to return the canonical label. 

These labels will connect together various objects within the application such as characters, games, and game engines. Game engines will enforce and allow the actions that GMs (and players) are able to perform in game in addition to normal posts. 

```
|Tag ID          | Display Name | Short Name | Aliases (json array?) |
| ------------- |:-------------:| -----:|
|1|Dungeons & Drangons (5th Edition) | DnD5e | ['d&d5e', 'dndnext']|
```

**Comment by mikelax** [comment]
@nazar  what do you think about this for the game labels table? I think it covers the basic structure of what we talked about earlier.

**Comment by nazar** [comment]
Hey @mikelax - the table structure looks sensible but I'm not convinced we need to store this in the database. A simpler alternative is that each game engine will store this data in a public `engine.metadata` object.

The API can then iterate through all existing game engines and return these on demand.

It's difficult to say at this early stage which way to go...

**Comment by mikelax** [comment]
hmm, my thoughts are that this `label` can be used to tie different components of the application together. Right now i see:  characters, games, and game engines. 

These labels can represent the game type we want to support, and I also thinking we would have a "generic" option to allow users to play a game that we haven't explicitly created yet. 

The values in this table can be used to drive the search in gamge lounge, act as a step 1 when creating a character or game. 
Another benefit of having the labels separate from engines is that it allows us to create some of the other objects without necessarily needing the engine. 

I am nervous that the game engine could (will) be a large project, but we can get most of the MVP out the door without, ie. if we get the game creation, search, posting, character creation working. 
We can roll out the advanced features for the in-game functionality as users start to sign up for the MVP.

**Comment by mikelax** [comment]
@nazar  
🤕  I accidentally [pushed this change to master](https://github.com/mikelax/forgingadventures/commit/fc0313978a50c38d0586499907be0068ad6c9915) instead of a branch. I know there is still the question about this object, if we decide we don't need we can rollback the few affected files. 

Also, I know I modified the old migration file. I was thinking that after the next ticket of me adding the "users" shadow table so we have the concept of a userId we'll draw a line and start creating additional migration files.

**Comment by nazar** [comment]
Hey @mikelax - no worries :D; I keep changing migrations on my end as well. The labels code looks good - I'm sure this will evolve the closer we get to implementing the first engine.

**Comment by mikelax** [comment]
done in commit [fc0313978a50c38d0586499907be0068ad6c9915](https://github.com/mikelax/forgingadventures/commit/fc0313978a50c38d0586499907be0068ad6c9915)
