### ISSUE TITLE
Tidy API database layer

### ISSUE THREAD

**Issue by nazar** [mikelax/forgingadventures#9]
This ticket addresses tidying up the API database layer operations

- [x] implement `created_at` and `updated_at` population for db operations. This should be flexible enough to handle tables rows that are only created and do not require an `updated_at` column
- [x] ~~implement `deleted_at` for soft deletes. This should be an optional mechanism as not all tables will require a soft delete mechanism~~ Leaving this for now until it is needed for sake of expediency

**Comment by mikelax** [comment]
@nazar  remember you can use two `true` params for the timestamps() knex function to get the not null and default now() attributes on created and updated at.

**Comment by nazar** [comment]
yep @mikelax - I'll double check that, specifically how it works with `updated_at`
